import Head from 'next/head'
import BottomNav from './bottom-nav';
import PropTypes from 'prop-types';

const propTypes = {};

const defaultProps = {};

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:w-7/12 lg:w-6/12 xl:w-5/12 min-h-screen mx-auto overflow-x-hidden">
        {
          children
        }
        <BottomNav/>
      </main>
    </div>
  );
};

Layout.propTypes = propTypes;
Layout.defaultProps = defaultProps;

export default Layout;